#' Augment a text data set with features generated by Linguistic Inquiry Word Count (LIWC) software.
#'
#' @param file.path path to the LIWC output file
#' @param meta an optional data.frame containing document metadata.
#' @return a \code{data.frame} containing LIWC-generated features for a set of text documents.
#' @export

augment_with_LIWC = function(file.path, meta=NULL){
  
  lfeats = read.csv(file.path, header=TRUE)
  names(lfeats)[grep("Source",names(lfeats))]=lfeats[1,grep("Source",names(lfeats))]
  lfeats = lfeats[-c(1),]
  
  out = data.frame(cbind(meta, lfeats))
  return(out)
  
}


  